# Generated by Django 4.1.3 on 2022-11-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='photo',
            new_name='post',
        ),
    ]
